name: Actions workflow
on: [push]
jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: sample Actiopns
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Siva Shankar'
      # - name: Log Greeting Time
      #   run: echo "{{ steps.greet.output.time }}"
      # - name: Save state
      #   run: echo "{time}=$time" >> $GITHUB_ENV
      # - name: Log Greeting Time
      #   run: echo ${{ env.time }}
      - name: Save state
        run: echo "::save-state name={name}::{value}"
      - name: Set output
        run: echo "::set-output name={name}::{value}"