name: sample action workflow
on: [push]
jobs:
  sample-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: checkout
        uses: actions/checkout@v3
      - name: List Files after checkout
        run: |
          pwd
          ls
      - name: sample action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: siva
      - name: Log Greeting
        run: echo "issue resloved"
    